# .readthedocs.yaml
version: 2

submodules:
  include: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Upgrade pip to the latest version
      - pip install --upgrade pip
      # Install poetry
      - pip install poetry
      # - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --all-extras --with sortingExtension,algorithmExtension

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  #fail_on_warning: true
