# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: {python: "3.8"}
  jobs:
    pre_install:
      - pwd
      - pip install poetry #- make poetry-download
      - pip install -r docs/requirements.txt
      - poetry --version
      - poetry env use /home/docs/checkouts/readthedocs.org/user_builds/miv-os/envs/doc_patch/bin/python # $(which python)
      - make install

#Optionally declare the Python requirements required to build your docs
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
