# .readthedocs.yaml
version: 2

submodules:
  include: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: 
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install --upgrade pip
      
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - experiment
  system_packages: true

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  #fail_on_warning: true
