# .readthedocs.yaml
version: 2

submodules:
  include: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: {python: "3.10"}
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false  # Key
      - poetry config virtualenvs.prefer-active-python true
    post_install:
      - poetry install --all-extras

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  #fail_on_warning: true
