# .readthedocs.yaml
version: 2

submodules:
  include: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install --upgrade pip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - experiment

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  #fail_on_warning: true
