name: CI

on:
  push:
    branches: [ main, update-** ]
  pull_request:
    branches: [ '**' ]

jobs:
  report-coverage:  # Report coverage from python 3.8 and mac-os. May change later
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
    steps:
      - uses: actions/checkout@v4
      - uses: mpi4py/setup-mpi@v1
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: release
          architecture: ''
          linking-type: static
          github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
      - name: Install dependencies
        run: |
          #poetry lock --no-update
          poetry install --all-extras --with=algorithmExtension,sortingExtension,mpi
      # Set environment variables for coverage test. Coverage test is done using python 3.8
      - name: Test MiV-OS using pytest
        run: |
          make test_ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
          file: ./coverage.xml
